name: main CI/CD pipeline
concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

# Key npm scripts from package.json:
# - test:unit: run unit tests
# - test:e2e: run end-to-end tests
# - build: production build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            e2e:
              - "src/**"
              - "tests/e2e/**"
              - ".github/workflows/main.yml"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Lint code
        run: pnpm run lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: lint
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Run unit tests
        run: pnpm run test:unit

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: [lint, changes]
    if: needs.changes.outputs.e2e == 'true'
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Run e2e tests
        run: pnpm run test:e2e

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [unit-test, e2e-test]
    if: ${{ always() && needs.unit-test.result == 'success' && (needs.e2e-test.result == 'success' || needs.e2e-test.result == 'skipped') }}
    env:
      NODE_ENV: production
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Build production
        run: pnpm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: [lint, unit-test, build]
    if: ${{ always() && needs.lint.result == 'success' && needs.unit-test.result == 'success' && needs.build.result == 'success' }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ai-flashcards
          directory: dist
