name: main CI/CD pipeline
concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

# Key npm scripts from package.json:
# - test:unit: run unit tests
# - test:e2e: run end-to-end tests
# - build: production build

on:
  push:
    branches:
      - main
      - clouflare-deploy
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Lint code
        run: pnpm run lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: lint
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Run unit tests
        run: pnpm run test:unit

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit-test
    if: ${{ always() && needs.unit-test.result == 'success' }}
    env:
      NODE_ENV: production
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common setup
        uses: ./.github/actions/common-setup
      - name: Build production
        run: pnpm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
